logging.config=classpath:logback-base.xml

pn.env.runtime=PROD
spring.application.name=pn-delivery-push-validator

management.endpoints.web.exposure.include=health,metrics,loggers
spring.cloud.aws.sqs.enabled=${SQS_INTEGRATION_ENABLED}

# Application parameters
pn.middleware.impl.document-creation=dynamo

pn.delivery-push.data-vault-base-url=http://alb.confidential.pn.internal:8080

# abilita il check del formato del pdf
pn.delivery-push-validator.check-pdf-valid-enabled=true
# abilita e configura il check sul size dei documenti, se <0 si intende disabilitato
pn.delivery-push-validator.check-pdf-size=200MB

pn.delivery-push-validator.safe-storage-cx-id=pn-delivery-push
pn.delivery-push-validator.safe-storage-cx-id-updatemetadata=pn-delivery

pn.legalfacts.generator=OPENHTML2PDF

pn.delivery-push-validator.time-params.waiting-for-read-courtesy-message=7d
pn.delivery-push-validator.time-params.second-notification-workflow-waiting-time=7d
pn.delivery-push-validator.time-params.scheduling-days-success-digital-refinement=7d
pn.delivery-push-validator.time-params.scheduling-days-failure-digital-refinement=15d
pn.delivery-push-validator.time-params.scheduling-days-success-analog-refinement=10d
pn.delivery-push-validator.time-params.scheduling-days-failure-analog-refinement=10d
pn.delivery-push-validator.time-params.notification-non-visibility-time=21:00
pn.delivery-push-validator.time-params.time-to-add-in-non-visibility-time-case=1d

# Config giorni retention degli allegati dopo la data di presa visione o decorrenza termini
pn.delivery-push-validator.retention-attachment-days-after-refinement=120

#Check codice fiscale
pn.delivery-push-validator.check-cf-enabled=false

pn.cache.enabled=true
pn.cache.cacheNames=aooSenderIdCache(100000)

#Indica il costo base della notifica per pagoPa
pn.delivery-push-validator.pagopa-notification-base-cost=100

pn.delivery-push-validator.list-categories-pa=REQUEST_REFUSED,REQUEST_ACCEPTED,SEND_DIGITAL_DOMICILE,SEND_DIGITAL_FEEDBACK,DIGITAL_SUCCESS_WORKFLOW,DIGITAL_FAILURE_WORKFLOW,SEND_SIMPLE_REGISTERED_LETTER,SEND_SIMPLE_REGISTERED_LETTER_PROGRESS,SEND_ANALOG_DOMICILE,SEND_ANALOG_PROGRESS,SEND_ANALOG_FEEDBACK,ANALOG_SUCCESS_WORKFLOW,ANALOG_FAILURE_WORKFLOW,COMPLETELY_UNREACHABLE,REFINEMENT,NOTIFICATION_VIEWED,NOTIFICATION_CANCELLED,NOTIFICATION_RADD_RETRIEVED,ANALOG_WORKFLOW_RECIPIENT_DECEASED

#Default value
pn.delivery-push-validator.pn-send-mode=1970-01-01T00:00:00Z;AAR-DOCUMENTS-PAYMENTS;AAR;AAR;AAR_NOTIFICATION,2024-02-13T23:00:00Z;AAR-DOCUMENTS-PAYMENTS;AAR;AAR-DOCUMENTS-PAYMENTS;AAR_NOTIFICATION,2024-03-31T23:00:00Z;AAR;AAR;AAR-DOCUMENTS-PAYMENTS;AAR_NOTIFICATION_RADD
pn.delivery-push-validator.safe-storage-file-not-found-retry=false
pn.delivery-push-validator.send-more-than-20-grams-default-value=false


pn.delivery-push-validator.templateURLforPEC=${PN_DELIVERY_PUSH_TEMPLATEURLFORPEC:/templates-engine-private/v1/templates/notification-aar-for-pec}