logging.config=classpath:logback-base.xml

pn.env.runtime=PROD
spring.application.name=pn-delivery-push-validator

management.endpoints.web.exposure.include=health,metrics,loggers
spring.cloud.aws.sqs.enabled=${SQS_INTEGRATION_ENABLED}

# Application parameters
pn.middleware.impl.document-creation=dynamo

pn.delivery-push.data-vault-base-url=http://alb.confidential.pn.internal:8080

# abilita il check del formato del pdf
pn.delivery-push-validator.check-pdf-valid-enabled=true
# abilita e configura il check sul size dei documenti, se <0 si intende disabilitato
pn.delivery-push-validator.check-pdf-size=200MB

pn.delivery-push-validator.safe-storage-cx-id=pn-delivery-push
pn.delivery-push-validator.safe-storage-cx-id-updatemetadata=pn-delivery

pn.legalfacts.generator=OPENHTML2PDF
#Check codice fiscale
pn.delivery-push-validator.check-cf-enabled=false

#Default value
pn.delivery-push-validator.safe-storage-file-not-found-retry=false
pn.delivery-push-validator.send-more-than-20-grams-default-value=false
