package it.pagopa.pn.deliverypushvalidator.exception;

import it.pagopa.pn.commons.exceptions.PnExceptionsCodes;
import lombok.Getter;

public class PnDeliveryPushValidatorExceptionCodes extends PnExceptionsCodes {

    // raccolgo qui tutti i codici di errore di delivery push
    public static final String ERROR_CODE_DELIVERYPUSH_NOTFOUND = "PN_DELIVERYPUSH_NOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_GETFILEERROR = "PN_DELIVERYPUSH_GETFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_UPLOADFILEERROR = "PN_DELIVERYPUSH_UPLOADFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_UPDATEMETAFILEERROR = "PN_DELIVERYPUSH_UPDATEMETAFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_ERRORCOMPUTECHECKSUM = "PN_DELIVERYPUSH_ERRORCOMPUTECHECKSUM";
    public static final String ERROR_CODE_DELIVERYPUSH_ATTACHMENTCHANGESTATUSFAILED = "PN_DELIVERYPUSH_ATTACHMENTCHANGESTATUSFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_INVALIDEVENTCODE = "PN_DELIVERYPUSH_INVALIDEVENTCODE";
    public static final String ERROR_CODE_DELIVERYPUSH_ROOTIDNOTFOUND = "PN_DELIVERYPUSH_ROOTIDNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_AUDITLOGFAILED = "PN_DELIVERYPUSH_AUDITLOGFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_SAVELEGALFACTSFAILED = "PN_DELIVERYPUSH_SAVELEGALFACTSFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_HANDLEEVENTFAILED = "PN_DELIVERYPUSH_HANDLEEVENTFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_ACTIONTYPENOTSUPPORTED = "PN_DELIVERYPUSH_ACTIONTYPENOTSUPPORTED";
    public static final String ERROR_CODE_DELIVERYPUSH_NO_RECIPIENT_IN_NOTIFICATION = "PN_DELIVERYPUSH_NORECIPIENTINNOTIFICATION";
    public static final String ERROR_CODE_DELIVERYPUSH_NOTIFICATIONFAILED = "PN_DELIVERYPUSH_NOTIFICATIONFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_NO_DOCUMENT_CREATION_REQUEST = "PN_DELIVERYPUSH_NO_DOCUMENT_CREATION_REQUEST";
    public static final String ERROR_CODE_DELIVERYPUSH_READ_FILE_ERROR = "PN_DELIVERYPUSH_READ_FILE_ERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_NORMALIZE_ADDRESS_ERROR = "PN_DELIVERYPUSH_NORMALIZE_ADDRESS_ERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_SENDER_ID_NOT_VALID = "PN_DELIVERYPUSH_SENDER_ID_NOT_VALID";
    public static final String ERROR_CODE_DELIVERYPUSH_PHYSICAL_ADDRESS_NOT_PRESENT = "PN_DELIVERYPUSH_PHYSICAL_ADDRESS_NOT_PRESENT";
    public static final String ERROR_CODE_DELIVERYPUSH_FILE_NOT_FOUND = "PN_DELIVERYPUSH_FILE_NOT_FOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_MESSAGE_NOT_FOUND = "PN_DELIVERYPUSH_MESSAGE_NOT_FOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_PAYMENT_UPDATE_RETRY_EXCEPTION = "ERROR_CODE_DELIVERYPUSH_PAYMENTUPDATERETRYEXCEPTION";
    public static final String ERROR_CODE_DELIVERYPUSH_TOTAL_COST_NOT_PRESENT = "ERROR_CODE_DELIVERYPUSH_TOTALCOSTNOTPRESENT";
    public static final String ERROR_CODE_DATAVAULT_FAILED = "ERROR_CODE_DATAVAULT_FAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_FILE_GONE = "PN_DELIVERYPUSH_FILE_GONE";
    public static final String ERROR_CODE_DELIVERYPUSH_ROUTER_INVALID_SUPPORTED_EVENT = "PN_DELIVERYPUSH_ROUTER_INVALID_SUPPORTED_EVENT";
    public static final String ERROR_CODE_DELIVERYPUSH_ROUTER_MULTIPLE_HANDLERS_FOUND = "PN_DELIVERYPUSH_ROUTER_MULTIPLE_HANDLERS_FOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_ROUTER_DESERIALIZATION = "PN_DELIVERYPUSH_ROUTER_DESERIALIZATION";
    public static final String ERROR_CODE_DELIVERYPUSH_ROUTER_EVENT_TYPE_MISSING = "PN_DELIVERYPUSH_ROUTER_EVENT_TYPE_MISSING";
    public static final String ERROR_CODE_DELIVERYPUSH_ROUTER_HANDLER_NOT_FOUND = "PN_DELIVERYPUSH_ROUTER_NOT_FOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_NOTIFICATION_COST_ERROR = "PN_DELIVERYPUSH_NOTIFICATION_COST_ERROR";


    public static final String ERROR_CODE_DELIVERY_PUSH_NOTIFICATION_NOT_ACCEPTED = "PN_DELIVERY_PUSH_NOTIFICATION_NOT_ACCEPTED";
    public static final String ERROR_CODE_DELIVERYPUSH_INVALID_PHYSICALADDRESS = "PN_DELIVERYPUSH_PHYSICALADDRESS_REQUIRED";
    public static final String ERROR_CODE_DELIVERYPUSH_LOOKUPADDRESS_INCONSISTENT_DATA = "PN_DELIVERYPUSH_LOOKUPADDRESS_INCONSISTENT_DATA";

    public static final String ERROR_CODE_DELIVERYPUSH_FUTURE_ACTION_NOTFOUND= "PN_ACTIONMANAGER_ERROR_CODE_FUTURE_ACTION_NOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_ACTION_CONFLICT = "PN_ACTIONMANAGER_ERROR_CODE_ACTION_CONFLICT";
    public static final String ERROR_CODE_TIMELINESERVICE_TIMELINE_ELEMENT_NOT_PRESENT = "PN_TIMELINESERVICE_TIMELINEELEMENTNOTPRESENT";

    public static final String ERROR_CODE_DELIVERYPUSH_CAMPAIGN_NOT_FOUND = "PN_DELIVERY_CAMPAIGN_NOT_FOUND";

    @Getter
    public enum NotificationRefusedErrorCodeInt {
        FILE_NOTFOUND("FILE_NOTFOUND", false),

        FILE_SHA_ERROR( "FILE_SHA_ERROR", false),

        FILE_PDF_INVALID_ERROR( "FILE_PDF_INVALID_ERROR", false),

        FILE_PDF_TOOBIG_ERROR( "FILE_PDF_TOOBIG_ERROR", false),

        TAXID_NOT_VALID("TAXID_NOT_VALID", false),

        NOT_VALID_ADDRESS("NOT_VALID_ADDRESS", false),

        F24_METADATA_NOT_VALID("F24_METADATA_NOT_VALID", false),
        
        SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE", false),

        RECIPIENT_ID_NOT_VALID("RECIPIENT_ID_NOT_VALID", false),

        PAYMENT_NOT_VALID("PAYMENT_NOT_VALID", false),
        //quickWorkAroundForPN-9116
        SENDER_DISABLED_MORE_THAN_20_GRAMS("SENDER_DISABLED_MORE_THAN_20_GRAMS", false),

        FILE_GONE("FILE_GONE", false),

        ADDRESS_NOT_FOUND("ADDRESS_NOT_FOUND", false),

        ADDRESS_SEARCH_FAILED("ADDRESS_SEARCH_FAILED", true),

        MESSAGE_NOT_FOUND("MESSAGE_NOT_FOUND", false),

        MESSAGE_LANGUAGE_MISMATCH("MESSAGE_LANGUAGE_MISMATCH", false);


        private final String value;

        private final Boolean isTechnicalRefusal;

        NotificationRefusedErrorCodeInt(String value, Boolean isTechnicalRefusal) {
            this.value = value;
            this.isTechnicalRefusal = isTechnicalRefusal;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static NotificationRefusedErrorCodeInt fromValue(String value) {
            for (NotificationRefusedErrorCodeInt b : NotificationRefusedErrorCodeInt.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            return null;
        }
    }
}
