AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

  LogRetention:
    Type: Number
    Default: 14
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  AlarmSNSTopicArn:
    Type: String

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

Resources:
  
  PnDeliveryPushValidatorServiceLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-delivery-push-validator-service'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

  PnNotificationCostToDeliveryPushValidatorQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-notification_cost_service_to_delivery_push_validator'
        HasDLQ: "true"
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60

Outputs:
  # Log groups
  EcsValidatorLogGroup:
    Value: !GetAtt PnDeliveryPushValidatorServiceLogGroup.Outputs.LogGroupName

  PnNotificationCostToDeliveryPushValidatorQueueName:
    Value: !GetAtt PnNotificationCostToDeliveryPushValidatorQueue.Outputs.QueueName
    Description: pn-notification-cost-to-delivery-push-validator queue name

  PnNotificationCostToDeliveryPushValidatorQueueURL:
    Value: !GetAtt PnNotificationCostToDeliveryPushValidatorQueue.Outputs.QueueURL
    Description: pn-notification-cost-to-delivery-push-validator queue URL

  PnNotificationCostToDeliveryPushValidatorQueueARN:
    Value: !GetAtt PnNotificationCostToDeliveryPushValidatorQueue.Outputs.QueueARN
    Description: pn-notification-cost-to-delivery-push-validator queue ARN

  PnNotificationCostToDeliveryPushValidatorQueueAlarmARN:
    Value: !GetAtt PnNotificationCostToDeliveryPushValidatorQueue.Outputs.SqsDLQAlarmArn
    Description: pn-notification-cost-to-delivery-push-validator alarm ARN

  PnNotificationCostToDeliveryPushValidatorQueueAgeAlarmARN:
    Value: !GetAtt PnNotificationCostToDeliveryPushValidatorQueue.Outputs.SqsAgeAlarmArn
    Description: pn-notification-cost-to-delivery-push-validator age alarm ARN
    