logging.config=config/logback-local.xml

# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD

spring.cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

pn.delivery-push-validator.document-creation-request-dao.table-name=DocumentCreationRequest
# Queue SQS configurations
pn.delivery-push-validator.topics.delivery-validation-events=local-delivery-push-inputs.fifo
pn.delivery-push-validator.topics.safe-storage-events=local-safe-storage-inputs
pn.delivery-push-validator.topics.validation-actions=local-validation-actions-inputs
pn.delivery-push-validator.topics.address-manager-events=local-address-manager-inputs
pn.delivery-push-validator.topics.f24-events=local-f24-inputs
spring.cloud.aws.sqs.enabled=true
