logging.config=config/logback-local.xml

spring.application.name=pn-delivery-push-validator

# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD

spring.cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

pn.delivery-push-validator.document-creation-request-dao.table-name=DocumentCreationRequest

