logging.config=config/logback-local.xml

spring.application.name=pn-delivery-push-validator

# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD

spring.cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

aws.region-code=us-east-1
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.endpoint-url=http://localhost:4566

pn.delivery-push-validator.document-creation-request-dao.table-name=DocumentCreationRequest

# Queue SQS configurations
pn.delivery-push-validator.topics.delivery-validation-events=local-delivery-push-inputs.fifo
pn.delivery-push-validator.topics.safe-storage-events=local-safe-storage-inputs
pn.delivery-push-validator.topics.validation-actions=local-validation-actions-inputs
pn.delivery-push-validator.topics.address-manager-events=local-address-manager-inputs
pn.delivery-push-validator.topics.f24-events=local-f24-inputs
pn.delivery-push-validator.topics.pn-notification-cost-to-delivery-push-validator-events=local-pn-notification-cost-to-delivery-push-validator-inputs
spring.cloud.aws.sqs.enabled=true

pn.delivery-push-validator.delivery-base-url=http://localhost:8080
pn.delivery-push-validator.data-vault-base-url=http://localhost:8084
pn.delivery-push-validator.safe-storage-base-url=http://localhost:8120
pn.delivery-push-validator.external-registry-base-url=http://localhost:8087
pn.delivery-push-validator.national-registries-base-url=http://localhost:1080
pn.delivery-push-validator.address-manager-base-url=http://localhost:8090
pn.delivery-push-validator.action-manager-base-url=http://localhost:8090
pn.delivery-push-validator.templates-engine-base-url=http://localhost:8090
pn.delivery-push-validator.timeline-client-base-url=http://localhost:8091
pn.delivery-push-validator.notification-cost-service-base-url=http://localhost:8092

pn.delivery-push-validator.address-manager-api-key="testApiKey"

# Enables retry of the notification validation in case of SafeStorage 404 error
pn.delivery-push-validator.safeStorageFileNotFoundRetry=false

pn.delivery-push-validator.timeline-client-enabled-start-date=2025-06-13T15:13:00Z

#Tempo di attesa che intercorre tra ogni ritentativo di validazione della notifica. Un tempo negativo (-1) sta ad indicare che i retry dovranno proseguire all'infinito, il tempo di attesa in questo caso sar� quello immediatamente precedente al tempo negativo definito
pn.delivery-push.validation-retry-intervals=10s, 1m, 1m, 5m, 1h, -1s

#Time to live delle action 0d significa disabilitato
pn.delivery-push-validator.action-ttl-days=1095

# abilita il check del formato del pdf
pn.delivery-push-validator.check-pdf-valid-enabled=true
# abilita e configura il check sul size dei documenti, se <0 si intende disabilitato
pn.delivery-push-validator.check-pdf-size=200MB

pn.delivery-push-validator.f24-cx-id=pn-delivery-push
pn.delivery-push-validator.safe-storage-cx-id=pn-delivery-push
pn.delivery-push-validator.safe-storage-cx-id-updatemetadata=pn-delivery

pn.delivery-push-validator.pago-pa-notification-base-cost=100

pn.delivery-push-validator.templateURLforPEC=${PN_DELIVERY_PUSH_TEMPLATEURLFORPEC:/templates-engine-private/v1/templates/notification-aar-for-pec}

# Attachment retention after validation.
# Note: This number is defined on safeStorage, so a change to these properties does not imply a change to effective file retention
pn.delivery-push-validator.time-params.attachment-retention-time-after-validation=120d

# Defines how long before the attachment retention expires need to start "check attachment retention"
pn.delivery-push-validator.time-params.check-attachment-time-before-expiration=10d

pn.delivery-push-validator.send-more-than-20-grams-default-value=false
pn.delivery-push-validator.additional-langs-enabled=true
pn.delivery-push-validator.technical-refusal-cost-mode=RECIPIENT_BASED;50

pn.delivery-push-validator.error-correction-level-qr-code=h